# This file is machine-generated - editing it directly is not advised

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[TOML]]
deps = ["Dates"]
git-tree-sha1 = "70c12a7129b147aa9e43325c86f32f7fbb88245a"
repo-rev = "master"
repo-url = "https://github.com/wildart/TOML.jl.git"
uuid = "191fdcea-f9f2-43e0-b922-d33f71e2abc3"
version = "0.4.0"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
